server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/chelotonio/idea
          search-paths: server/config-data
  application:
    name: config-service

